### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by toufa123** [chartit/django-chartit#57]
'NoneType' object is not subscriptable

Exception Value: | 'NoneType' object is not subscriptable
-- | --
C:\Python36\lib\site-packages\chartit\templatetags\chartit.py in load_charts, line 86

**Comment by atodorov** [comment]
Please post the full traceback of the error as well as the code which triggers it.

**Comment by toufa123** [comment]
I'm using django 2.01 and django-chartit 0.2.9

def NIS_by_Status_view(request):
    # Step 1: Create a DataPool with the data we want to retrieve.
    ds = \
        DataPool(
            series=
            [{'options': {
                'source': Aliens.objects.raw(
                    "SELECT status.medsucess AS Species Status, Count(aliens.id) AS Number FROM aliens INNER JOIN status ON aliens.status_id == status.id GROUP BY status.medsucess")},
                'terms': [
                    'Species Status',
                    'Number']}
            ])

    # Step 2: Create the Chart object
    cht = Chart(
        datasource=ds,
        series_options=
        [{'options': {
            'type': 'line',
            'stacking': False},
            'terms': {
                'Species Status': [
                    'Number']
            }}],
        chart_options=
        {'title': {
            'text': 'Number of NIS by Status'},
            'xAxis': {
                'title': {
                    'text': 'Species Status'}}})

    # Step 3: Send the chart object to the template.
    return render_to_response('mamias/dashboard.html', {'NISbySTATUS': cht})

dashboard.html

{% extends 'mamias/mamias.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MAMIAS | {% block title %} Dashboard {% endblock %}</title>


     {% load chartit %}
    {{ NISbySTATUS|load_charts:"container" }}

</head>
<div class="col-xs-12 col-lg-12 col-xl-6">
            <div class="card-box">

                <h4 class="header-title m-t-0 m-b-20">Number of NIS by Status</h4>

                <div class="text-center">

                </div>

                <div id="container" style="height: 320px;"></div>

            </div>
        </div>

**Comment by atodorov** [comment]
Post the python traceback.

Also post the results of your query.

**Comment by toufa123** [comment]
I'm new in Django and how I can get the result of the query

**Comment by atodorov** [comment]
> I'm new in Django and how I can get the result of the query

`./manage.py shell` and execute the query inside the shell. You will likely have to iterate over it to print the results.

**Comment by toufa123** [comment]
def query(request):
    objs = Aliens.objects.raw("SELECT status.medsucess AS SpeciesStatus, 1 id, Count(aliens.id) as Number FROM aliens INNER JOIN status ON aliens.status_id = status.id GROUP BY status.medsucess")
    for obj in objs:
        azerty = print ( obj.Number, obj.SpeciesStatus)

having problem 
Traceback (most recent call last):
  File "<input>", line 2, in <module>
AttributeError: 'Aliens' object has no attribute 'Number'

**Comment by atodorov** [comment]
your resulting object `obj` does not have an attribute with the name `.Number`. Please read Django's QuerySet API documentation and get your queries working before submitting any more comments to this issue.

This is not a general Django support forum, this issue tracker is meant *only* for issues related to django-chartit!

**Comment by toufa123** [comment]
here is the result of the query
[('native', 7), ('cryptogenic/casual', 10), ('invasive', 14), ('Established /invasive', 4), ('established', 97), ('Questionable/Established', 1), ('Questionable/Casual', 1), ('excluded', 25), ('range expansion', 1), ('casual', 107), ('questionable', 8), ('atlanic origin/invasive', 519), ('Range Expansion/Casual', 1), ('unknown', 8), ('cryptogenic', 291), ('cryptogenic/questionable', 61), ('cryptogenic/established', 267)]

**Comment by Dhrumin3103** [comment]
return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'                                                                                                        TypeError: 'NoneType' object is not subscriptable 
                                                                                                                                                                                                                                                                                              During handling of the above exception, another exception occurred:                                                                                                                                                                                                                                                                             Traceback (most recent call last):                                                                                                                                        File "C:\Users\DHRUMIN\.conda\envs\webscrape\lib\socketserver.py", line 654, in process_request_thread                                                                    self.finish_request(request, client_address)                                                                                                                          File "C:\Users\DHRUMIN\.conda\envs\webscrape\lib\socketserver.py", line 364, in finish_request                                                                            self.RequestHandlerClass(request, client_address, self)                                                                                                               File "C:\Users\DHRUMIN\.conda\envs\webscrape\lib\socketserver.py", line 724, in __init__                                                                                  self.handle()                                                                                                                                                         File "C:\Users\DHRUMIN\.conda\envs\webscrape\lib\site-packages\django\core\servers\basehttp.py", line 171, in handle                                                      self.handle_one_request()                                                                                                                                             File "C:\Users\DHRUMIN\.conda\envs\webscrape\lib\site-packages\django\core\servers\basehttp.py", line 194, in handle_one_request                                          handler.run(self.server.get_app())                                                                                                                                    File "C:\Users\DHRUMIN\.conda\envs\webscrape\lib\wsgiref\handlers.py", line 144, in run                                                                                   self.close()                                                                                                                                                          File "C:\Users\DHRUMIN\.conda\envs\webscrape\lib\site-packages\django\core\servers\basehttp.py", line 111, in close                                                       super().close()                                                                                                                                                       File "C:\Users\DHRUMIN\.conda\envs\webscrape\lib\wsgiref\simple_server.py", line 35, in close                                                                             self.status.split(' ',1)[0], self.bytes_sent                                                                                                                        AttributeError: 'NoneType' object has no attribute 'split'
